version: '3.8'

services:
  wallet-backend:
    build: .
    ports:
      - "8087:8087"
    environment:
      - GIN_MODE=release
      - SERVER_PORT=8087
      - CONFIG_PATH=/root/config/config.nnkong.yaml
    volumes:
      - ./config:/root/config:ro
      - ./keystores:/root/keystores
      - /var/log/wallet:/var/log/wallet
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wallet-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - wallet-backend
    restart: unless-stopped
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge